#!/usr/bin/env python3

"""
tacho - Tachometer for your apps

"""

__version_info__ = ('0', '1', '0')
__version__ = '.'.join(__version_info__)

if __name__ == '__main__':
    print("Hello, world! this is tacho.")
